version: "3.7"
services:
  omada:
    build: .
    image: pcarorevuelta/omada-controller
    container_name: omada-controller
    init: true
    ports:
      - 8080:8080/tcp
      - 8043:8043/tcp
      - 27001:27001/udp
      - 27002:27002/tcp
      - 29810:29810/udp
      - 29811:29811/tcp
      - 29812:29812/tcp
      - 29813:29813/tcp
    environment:
      - TZ=Europe/Copenhagen
    volumes:
      - ./omada-volumenes/logs:/opt/tplink/EAPController/logs
      - ./omada-volumenes/data:/opt/tplink/EAPController/data
      - ./omada-volumenes/work:/opt/tplink/EAPController/work
    restart: always
